<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "gs_be_dark_theme"
 *
 * Auto generated by Extension Builder 2017-02-24
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'BE dark theme',
	'description' => 'Distribution BE dark theme',
	'category' => 'distribution',
	'author' => 'Christian Hackl',
	'author_email' => 'hackl.chris@googlemail.com',
	'state' => 'alpha',
	'uploadfolder' => '0',
	'clearCacheOnLoad' => 0,
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '8.7.1-8.9.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
